In [ ]:
                                    # National Language Processing:(NLP) 
                        "From Words to Insights: Swiggy Review Sentiment Analysis using NLP 🤖"

## Overview This project applies **Natural Language Processing (NLP)** to analyze customer reviews from Swiggy. 

 ---The project aims to analyze customer reviews from Swiggy, one of India’s leading food delivery platforms, 
    using Natural Language Processing (NLP) techniques.
 ---The goal is to classify reviews into **Positive, Negative, and Neutral sentiments** to uncover insights about customer satisfaction.
 
Preprocessing:

---Text cleaning (removing stopwords, punctuation, special characters)
---Tokenization and lemmatization
---Handling imbalanced data

Feature Engineering:

--Bag of Words & TF-IDF
--Word embeddings (Word2Vec, GloVe)

Modeling:

Machine Learning: Logistic Regression, Random Forest
Deep Learning: LSTM, BERT (experimental)
Evaluation: Accuracy, Precision, Recall, F1-score, Confusion Matrix

📊 Key Insights
--Customers consistently praise fast delivery 🚚.
--Packaging issues 📦 are the most common source of negative reviews.
--Neutral reviews often highlight average food quality or mixed experiences.

🖥️ Tech Stack
Languages: Python
Libraries: pandas, numpy, matplotlib, seaborn, NLTK, scikit-learn, TensorFlow/Keras
Visualization: Word clouds, sentiment distribution charts, confusion matrices

🚀 Impact
--This project demonstrates how NLP can transform raw text into business intelligence,
  helping food delivery platforms improve customer experience by focusing on what matters most to users.

In [29]:
pip install nltk

Requirement already satisfied: nltk in c:\users\sathyanarayanan\anaconda3\lib\site-packages (3.9.1)
Requirement already satisfied: click in c:\users\sathyanarayanan\anaconda3\lib\site-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in c:\users\sathyanarayanan\anaconda3\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\sathyanarayanan\anaconda3\lib\site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\sathyanarayanan\anaconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\sathyanarayanan\anaconda3\lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [30]:
import nltk

In [31]:
# Download the popular datasets and corpora
nltk.download('popular')  # This downloads the most commonly used NLTK datasets

# Download the part-of-speech tagger
nltk.download('averaged_perceptron_tagger_eng')  # This downloads the POS tagger

[nltk_data] Downloading collection 'popular'
[nltk_data]    |
[nltk_data]    | Downloading package cmudict to
[nltk_data]    |     C:\Users\Sathyanarayanan\AppData\Roaming\nltk_dat
[nltk_data]    |     a...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package gazetteers to
[nltk_data]    |     C:\Users\Sathyanarayanan\AppData\Roaming\nltk_dat
[nltk_data]    |     a...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to
[nltk_data]    |     C:\Users\Sathyanarayanan\AppData\Roaming\nltk_dat
[nltk_data]    |     a...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to
[nltk_data]    |     C:\Users\Sathyanarayanan\AppData\Roaming\nltk_dat
[nltk_data]    |     a...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package inaugural to
[nltk_data]    |     C:\Users\Sathyanarayanan\AppData\Roaming\nltk_dat
[nltk_data]    |     a...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     C:\Users\Sathyanarayanan\AppData\Roaming\nltk_dat
[nltk_data]    |     a...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package names to
[nltk_data]    |     C:\Users\Sathyanarayanan\AppData\Roaming\nltk_dat
[nltk_data]    |     a...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Downloading package shakespeare to
[nltk_data]    |     C:\Users\Sathyanarayanan\AppData\Roaming\nltk_dat
[nltk_data]    |     a...
[nltk_data]    |   Package shakespeare is already up-to-date!
[nltk_data]    | Downloading package stopwords to
[nltk_data]    |     C:\Users\Sathyanarayanan\AppData\Roaming\nltk_dat
[nltk_data]    |     a...
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package treebank to
[nltk_data]    |     C:\Users\Sathyanarayanan\AppData\Roaming\nltk_dat
[nltk_data]    |     a...
[nltk_data]    |   Package treebank is already up-to-date!
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     C:\Users\Sathyanarayanan\AppData\Roaming\nltk_dat
[nltk_data]    |     a...
[nltk_data]    |   Package twitter_samples is already up-to-date!
[nltk_data]    | Downloading package omw to
[nltk_data]    |     C:\Users\Sathyanarayanan\AppData\Roaming\nltk_dat
[nltk_data]    |     a...
[nltk_data]    |   Package omw is already up-to-date!
[nltk_data]    | Downloading package omw-1.4 to
[nltk_data]    |     C:\Users\Sathyanarayanan\AppData\Roaming\nltk_dat
[nltk_data]    |     a...
[nltk_data]    |   Package omw-1.4 is already up-to-date!
[nltk_data]    | Downloading package wordnet to
[nltk_data]    |     C:\Users\Sathyanarayanan\AppData\Roaming\nltk_dat
[nltk_data]    |     a...
[nltk_data]    |   Package wordnet is already up-to-date!
[nltk_data]    | Downloading package wordnet2021 to
[nltk_data]    |     C:\Users\Sathyanarayanan\AppData\Roaming\nltk_dat
[nltk_data]    |     a...
[nltk_data]    |   Package wordnet2021 is already up-to-date!
[nltk_data]    | Downloading package wordnet31 to
[nltk_data]    |     C:\Users\Sathyanarayanan\AppData\Roaming\nltk_dat
[nltk_data]    |     a...
[nltk_data]    |   Package wordnet31 is already up-to-date!
[nltk_data]    | Downloading package wordnet_ic to
[nltk_data]    |     C:\Users\Sathyanarayanan\AppData\Roaming\nltk_dat
[nltk_data]    |     a...
[nltk_data]    |   Package wordnet_ic is already up-to-date!
[nltk_data]    | Downloading package words to
[nltk_data]    |     C:\Users\Sathyanarayanan\AppData\Roaming\nltk_dat
[nltk_data]    |     a...
[nltk_data]    |   Package words is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     C:\Users\Sathyanarayanan\AppData\Roaming\nltk_dat
[nltk_data]    |     a...
[nltk_data]    |   Package maxent_ne_chunker is already up-to-date!
[nltk_data]    | Downloading package punkt to
[nltk_data]    |     C:\Users\Sathyanarayanan\AppData\Roaming\nltk_dat
[nltk_data]    |     a...
[nltk_data]    |   Package punkt is already up-to-date!
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     C:\Users\Sathyanarayanan\AppData\Roaming\nltk_dat
[nltk_data]    |     a...
[nltk_data]    |   Package snowball_data is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\Sathyanarayanan\AppData\Roaming\nltk_dat
[nltk_data]    |     a...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    |
[nltk_data]  Done downloading collection popular
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\Sathyanarayanan\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

True

In [4]:
import nltk
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv("D:/Nivedhika_DA_Learning/swiggy.csv/swiggy.csv")
df

,App,review_date,review_description,rating,thumbsUpCount,developer_response,developer_response_date,appVersion
0,Swiggy,2023-07-24 09:57:40,I have been using swiggy for a long time and I...,2,103,"Hey there, we apologize for the inconvenience ...",2023-07-24 10:02:21,4.37.2
1,Swiggy,2023-07-23 10:35:23,Worst experiences I'm having with the app for ...,1,12,"Hello, we would like to know more about it. Pl...",2023-07-23 10:42:22,4.37.2
2,Swiggy,2023-07-24 14:48:26,The best foolishing app with offers. The app o...,1,7,We are sorry to let you down. Please write to ...,2023-07-24 14:52:22,4.37.2
3,Swiggy,2023-07-07 08:26:00,Title: Disappointing Experience with Swiggy In...,1,85,"Hey there, we are sorry to have put you throug...",2023-07-07 08:32:20,4.36.1
4,Swiggy,2023-07-19 07:40:05,Worst ever experience. I ordered from instamar...,1,29,We're apologetic about this experience you've ...,2023-07-19 07:42:22,4.36.3
...,...,...,...,...,...,...,...,...
200786,Swiggy,2019-01-09 08:24:54,Very Good Experience with Swiffy,5,0,"Hey Navjyot, we're pleased that you enjoyed yo...",2019-01-09 08:33:44,2.3.13
200787,Swiggy,2019-11-30 15:06:54,Good offers. Best food,5,0,"Hey, thanks for the rating! This motivates us ...",2019-11-30 15:16:20,3.12.0
200788,Swiggy,2019-12-10 11:49:51,It's real awesome fast delivery,5,0,"Hey, thanks for the rating! This motivates us ...",2019-12-10 11:56:12,3.12.0
200789,Swiggy,2019-11-11 11:32:01,"Super app, and healful",5,0,"Hey, thanks for the rating! This motivates us ...",2019-11-11 11:36:18,3.10.0
200790,Swiggy,2019-11-18 20:04:15,very user friendly,5,0,"Hi Arnav, thank you for the perfect stars and ...",2019-11-18 20:09:21,3.11.1

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200791 entries, 0 to 200790
Data columns (total 8 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   App                      200791 non-null  object
 1   review_date              200791 non-null  object
 2   review_description       200791 non-null  object
 3   rating                   200791 non-null  int64
 4   thumbsUpCount            200791 non-null  int64
 5   developer_response       197247 non-null  object
 6   developer_response_date  197247 non-null  object
 7   appVersion               170082 non-null  object
dtypes: int64(2), object(6)
memory usage: 12.3+ MB

In [7]:
df.head(5)

,App,review_date,review_description,rating,thumbsUpCount,developer_response,developer_response_date,appVersion
0,Swiggy,2023-07-24 09:57:40,I have been using swiggy for a long time and I...,2,103,"Hey there, we apologize for the inconvenience ...",2023-07-24 10:02:21,4.37.2
1,Swiggy,2023-07-23 10:35:23,Worst experiences I'm having with the app for ...,1,12,"Hello, we would like to know more about it. Pl...",2023-07-23 10:42:22,4.37.2
2,Swiggy,2023-07-24 14:48:26,The best foolishing app with offers. The app o...,1,7,We are sorry to let you down. Please write to ...,2023-07-24 14:52:22,4.37.2
3,Swiggy,2023-07-07 08:26:00,Title: Disappointing Experience with Swiggy In...,1,85,"Hey there, we are sorry to have put you throug...",2023-07-07 08:32:20,4.36.1
4,Swiggy,2023-07-19 07:40:05,Worst ever experience. I ordered from instamar...,1,29,We're apologetic about this experience you've ...,2023-07-19 07:42:22,4.36.3

In [8]:
df1=df[["review_description"]]

In [9]:
df1.head()

                                  review_description
0  I have been using swiggy for a long time and I...
1  Worst experiences I'm having with the app for ...
2  The best foolishing app with offers. The app o...
3  Title: Disappointing Experience with Swiggy In...
4  Worst ever experience. I ordered from instamar...

In [10]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Sathyanarayanan\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [11]:
word="the children play outside every evening"

a = nltk.word_tokenize(word)
print(a)


pos_tags = nltk.pos_tag(a)
print(pos_tags)

['the', 'children', 'play', 'outside', 'every', 'evening']
[('the', 'DT'), ('children', 'NNS'), ('play', 'VBP'), ('outside', 'JJ'), ('every', 'DT'), ('evening', 'NN')]

In [12]:
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\Sathyanarayanan\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

True

In [13]:
import re
def clean(text):
    text = re.sub('[^A-Za-z]+', ' ', text)
    return text

df1['Cleaned Reviews'] = df1['review_description'].apply(clean)
df1.head()

C:\Users\Sathyanarayanan\AppData\Local\Temp\ipykernel_12720\1565995942.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Cleaned Reviews'] = df1['review_description'].apply(clean)

,review_description,Cleaned Reviews
0,I have been using swiggy for a long time and I...,I have been using swiggy for a long time and I...
1,Worst experiences I'm having with the app for ...,Worst experiences I m having with the app for ...
2,The best foolishing app with offers. The app o...,The best foolishing app with offers The app of...
3,Title: Disappointing Experience with Swiggy In...,Title Disappointing Experience with Swiggy Ins...
4,Worst ever experience. I ordered from instamar...,Worst ever experience I ordered from instamart...

In [14]:
# example for split and join
hel="i am good at work"
c=hel.split()
print(c)
joined=" ".join(c)
joined

['i', 'am', 'good', 'at', 'work']

'i am good at work'

In [15]:
df1['Lowercase'] = df1['Cleaned Reviews'].apply(lambda x: " ".join(word.lower() for word in x.split()))

C:\Users\Sathyanarayanan\AppData\Local\Temp\ipykernel_12720\3051793729.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Lowercase'] = df1['Cleaned Reviews'].apply(lambda x: " ".join(word.lower() for word in x.split()))

In [16]:
df1.head()

,review_description,Cleaned Reviews,Lowercase
0,I have been using swiggy for a long time and I...,I have been using swiggy for a long time and I...,i have been using swiggy for a long time and i...
1,Worst experiences I'm having with the app for ...,Worst experiences I m having with the app for ...,worst experiences i m having with the app for ...
2,The best foolishing app with offers. The app o...,The best foolishing app with offers The app of...,the best foolishing app with offers the app of...
3,Title: Disappointing Experience with Swiggy In...,Title Disappointing Experience with Swiggy Ins...,title disappointing experience with swiggy ins...
4,Worst ever experience. I ordered from instamar...,Worst ever experience I ordered from instamart...,worst ever experience i ordered from instamart...

In [17]:
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
#stop_words.remove("no")
print(stop_words)

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [18]:
df1['stopwords'] = df1['Lowercase'].apply(lambda x: " ".join(word for word in x.split() if word not in stop_words))

C:\Users\Sathyanarayanan\AppData\Local\Temp\ipykernel_12720\4161203686.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['stopwords'] = df1['Lowercase'].apply(lambda x: " ".join(word for word in x.split() if word not in stop_words))

In [19]:
df1

,review_description,Cleaned Reviews,Lowercase,stopwords
0,I have been using swiggy for a long time and I...,I have been using swiggy for a long time and I...,i have been using swiggy for a long time and i...,using swiggy long time worked fine untill enco...
1,Worst experiences I'm having with the app for ...,Worst experiences I m having with the app for ...,worst experiences i m having with the app for ...,worst experiences app last couple months today...
2,The best foolishing app with offers. The app o...,The best foolishing app with offers The app of...,the best foolishing app with offers the app of...,best foolishing app offers app offered like on...
3,Title: Disappointing Experience with Swiggy In...,Title Disappointing Experience with Swiggy Ins...,title disappointing experience with swiggy ins...,title disappointing experience swiggy instamar...
4,Worst ever experience. I ordered from instamar...,Worst ever experience I ordered from instamart...,worst ever experience i ordered from instamart...,worst ever experience ordered instamart got it...
...,...,...,...,...
200786,Very Good Experience with Swiffy,Very Good Experience with Swiffy,very good experience with swiffy,good experience swiffy
200787,Good offers. Best food,Good offers Best food,good offers best food,good offers best food
200788,It's real awesome fast delivery,It s real awesome fast delivery,it s real awesome fast delivery,real awesome fast delivery
200789,"Super app, and healful",Super app and healful,super app and healful,super app healful
200790,very user friendly,very user friendly,very user friendly,user friendly

In [20]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import wordnet
from nltk import pos_tag

# Download necessary NLTK data files
nltk.download('punkt')
nltk.download('wordnet')    #WordNet is a large lexical database of English 

# POS tagger dictionary
pos_dict = {'J': wordnet.ADJ, 'V': wordnet.VERB, 'N': wordnet.NOUN, 'R': wordnet.ADV}

def token_pos(text):
    return [
        (word, pos_dict.get(tag[0]))
        for word, tag in pos_tag(word_tokenize(text))
    ]

# Apply to your data
df1['POS tagged'] = df1['stopwords'].apply(token_pos)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Sathyanarayanan\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Sathyanarayanan\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
C:\Users\Sathyanarayanan\AppData\Local\Temp\ipykernel_12720\2017689350.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['POS tagged'] = df1['stopwords'].apply(token_pos)

In [21]:
df1.head()

,review_description,Cleaned Reviews,Lowercase,stopwords,POS tagged
0,I have been using swiggy for a long time and I...,I have been using swiggy for a long time and I...,i have been using swiggy for a long time and i...,using swiggy long time worked fine untill enco...,"[(using, v), (swiggy, a), (long, a), (time, n)..."
1,Worst experiences I'm having with the app for ...,Worst experiences I m having with the app for ...,worst experiences i m having with the app for ...,worst experiences app last couple months today...,"[(worst, a), (experiences, n), (app, v), (last..."
2,The best foolishing app with offers. The app o...,The best foolishing app with offers The app of...,the best foolishing app with offers the app of...,best foolishing app offers app offered like on...,"[(best, a), (foolishing, n), (app, n), (offers..."
3,Title: Disappointing Experience with Swiggy In...,Title Disappointing Experience with Swiggy Ins...,title disappointing experience with swiggy ins...,title disappointing experience swiggy instamar...,"[(title, n), (disappointing, a), (experience, ..."
4,Worst ever experience. I ordered from instamar...,Worst ever experience I ordered from instamart...,worst ever experience i ordered from instamart...,worst ever experience ordered instamart got it...,"[(worst, r), (ever, r), (experience, r), (orde..."

In [32]:
from nltk.stem import WordNetLemmatizer

# Initialize the lemmatizer
wordnet_lemmatizer = WordNetLemmatizer()

def lemmatize(pos_data):
    ans = " "
    for word, pos in pos_data:
        if not pos:  # If no POS tag is available, use the word as is
            lemma = word
        else:
            # Lemmatize based on the POS tag
            lemma = wordnet_lemmatizer.lemmatize(word, pos=pos)
        ans = ans + " " + lemma  # Add the lemma to the result string
    return ans

# Assuming df2 is your dataframe and 'POS tagged' contains POS-tagged text
df1['Lemma'] = df1['POS tagged'].apply(lemmatize)

C:\Users\Sathyanarayanan\AppData\Local\Temp\ipykernel_12720\3443675895.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Lemma'] = df1['POS tagged'].apply(lemmatize)

In [23]:
df1.head()

,review_description,Cleaned Reviews,Lowercase,stopwords,POS tagged,Lemma
0,I have been using swiggy for a long time and I...,I have been using swiggy for a long time and I...,i have been using swiggy for a long time and i...,using swiggy long time worked fine untill enco...,"[(using, v), (swiggy, a), (long, a), (time, n)...",use swiggy long time work fine untill encoun...
1,Worst experiences I'm having with the app for ...,Worst experiences I m having with the app for ...,worst experiences i m having with the app for ...,worst experiences app last couple months today...,"[(worst, a), (experiences, n), (app, v), (last...",bad experience app last couple month today w...
2,The best foolishing app with offers. The app o...,The best foolishing app with offers The app of...,the best foolishing app with offers the app of...,best foolishing app offers app offered like on...,"[(best, a), (foolishing, n), (app, n), (offers...",best foolishing app offer app offer like one...
3,Title: Disappointing Experience with Swiggy In...,Title Disappointing Experience with Swiggy Ins...,title disappointing experience with swiggy ins...,title disappointing experience swiggy instamar...,"[(title, n), (disappointing, a), (experience, ...",title disappointing experience swiggy instam...
4,Worst ever experience. I ordered from instamar...,Worst ever experience I ordered from instamart...,worst ever experience i ordered from instamart...,worst ever experience ordered instamart got it...,"[(worst, r), (ever, r), (experience, r), (orde...",worst ever experience ordered instamart get ...

In [33]:
df.head()

,App,review_date,review_description,rating,thumbsUpCount,developer_response,developer_response_date,appVersion
0,Swiggy,2023-07-24 09:57:40,I have been using swiggy for a long time and I...,2,103,"Hey there, we apologize for the inconvenience ...",2023-07-24 10:02:21,4.37.2
1,Swiggy,2023-07-23 10:35:23,Worst experiences I'm having with the app for ...,1,12,"Hello, we would like to know more about it. Pl...",2023-07-23 10:42:22,4.37.2
2,Swiggy,2023-07-24 14:48:26,The best foolishing app with offers. The app o...,1,7,We are sorry to let you down. Please write to ...,2023-07-24 14:52:22,4.37.2
3,Swiggy,2023-07-07 08:26:00,Title: Disappointing Experience with Swiggy In...,1,85,"Hey there, we are sorry to have put you throug...",2023-07-07 08:32:20,4.36.1
4,Swiggy,2023-07-19 07:40:05,Worst ever experience. I ordered from instamar...,1,29,We're apologetic about this experience you've ...,2023-07-19 07:42:22,4.36.3

In [ ]:
rating       ans       
    3         neutral
    1         negative
    5         positive

In [37]:
def scores(RATES):
    if RATES > 3:  # Positive threshold
        return 0   # positive
    elif RATES < 3:  # Negative threshold
        return 1 # negative
    else:
        return 2 # neutral
df["scores"]=df["rating"].apply(scores)

In [38]:
df

,App,review_date,review_description,rating,thumbsUpCount,developer_response,developer_response_date,appVersion,scores
0,Swiggy,2023-07-24 09:57:40,I have been using swiggy for a long time and I...,2,103,"Hey there, we apologize for the inconvenience ...",2023-07-24 10:02:21,4.37.2,1
1,Swiggy,2023-07-23 10:35:23,Worst experiences I'm having with the app for ...,1,12,"Hello, we would like to know more about it. Pl...",2023-07-23 10:42:22,4.37.2,1
2,Swiggy,2023-07-24 14:48:26,The best foolishing app with offers. The app o...,1,7,We are sorry to let you down. Please write to ...,2023-07-24 14:52:22,4.37.2,1
3,Swiggy,2023-07-07 08:26:00,Title: Disappointing Experience with Swiggy In...,1,85,"Hey there, we are sorry to have put you throug...",2023-07-07 08:32:20,4.36.1,1
4,Swiggy,2023-07-19 07:40:05,Worst ever experience. I ordered from instamar...,1,29,We're apologetic about this experience you've ...,2023-07-19 07:42:22,4.36.3,1
...,...,...,...,...,...,...,...,...,...
200786,Swiggy,2019-01-09 08:24:54,Very Good Experience with Swiffy,5,0,"Hey Navjyot, we're pleased that you enjoyed yo...",2019-01-09 08:33:44,2.3.13,0
200787,Swiggy,2019-11-30 15:06:54,Good offers. Best food,5,0,"Hey, thanks for the rating! This motivates us ...",2019-11-30 15:16:20,3.12.0,0
200788,Swiggy,2019-12-10 11:49:51,It's real awesome fast delivery,5,0,"Hey, thanks for the rating! This motivates us ...",2019-12-10 11:56:12,3.12.0,0
200789,Swiggy,2019-11-11 11:32:01,"Super app, and healful",5,0,"Hey, thanks for the rating! This motivates us ...",2019-11-11 11:36:18,3.10.0,0
200790,Swiggy,2019-11-18 20:04:15,very user friendly,5,0,"Hi Arnav, thank you for the perfect stars and ...",2019-11-18 20:09:21,3.11.1,0

In [ ]:
X=df1[["Lemma"]]
y=df["scores"]

In [50]:
X=df1["Lemma"]
y=df["scores"]

In [51]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [52]:
# Create a Bag-of-Words representation of the text data
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

In [53]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

In [54]:
X_train

54955       love ui service option grievance handle also...
90131       cheat pick call pay guy deliver swiggy charg...
141982                 ita really good well zomato ubereats
99144                  sometimes feel tax high coupon bluff
61431       really good delivery boy rude might take tim...
                                ...
119879             awesome app userfriendly less order time
103694                           easy order good experience
131932                             place cash delivery rate
146867                          trust app time cancel order
121958                nice excellent service ontime service
Name: Lemma, Length: 160632, dtype: object

In [57]:
X_train_tfidf

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1837344 stored elements and shape (160632, 5000)>

In [56]:
from sklearn.naive_bayes import MultinomialNB
nb_model = MultinomialNB()
nb_model.fit(X_train_tfidf, y_train)

MultinomialNB()

In [59]:
print(len(X_train))
print(X_train_tfidf.shape)
y_pred = nb_model.predict(X_test_tfidf)

160632
(160632, 5000)

In [60]:
from sklearn.metrics import accuracy_score
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.8822679847605767

                                     ** Accuracy --88 % **